export const GET_LAUNCH_DETAILS_SUCCESS = 'GET_LAUNCH_DETAILS_SUCCESS'
export const GET_LAUNCH_DETAILS_FAILURE = 'GET_LAUNCH_DETAILS_FAILURE'
export const GET_LAUNCH_FILTER_SUCCESS = 'GET_LAUNCH_FILTER_SUCCESS'
export const GET_DATE_FILTER_SUCCESS = 'GET_DATE_FILTER_SUCCESS'